site_name: AllenAct
site_description: A framework for Embodied AI research
site_url: https://github.com/allenai/allenact

theme:
  name: material
  palette:
    primary: blue
    accent: grey
  logo: img/AI2_Avatar_White.png
  favicon: img/AllenAct_A.svg
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json


repo_name: allenai/allenact
repo_url: https://github.com/allenai/allenact
edit_uri: edit/master/docs/
docs_dir: docs

nav:
- Overview: index.md
- Installation:
  - Install AllenAct: installation/installation-allenact.md
  - Install environments: installation/installation-framework.md
- Getting started:
  - Run your first experiment: getting_started/running-your-first-experiment.md
  - Structure of the codebase: getting_started/structure.md
  - Primary abstractions: getting_started/abstractions.md
- Tutorials:
  - AllenAct Tutorials: tutorials/index.md
  - Navigation in Minigrid: tutorials/minigrid-tutorial.md
  - PointNav in RoboTHOR: tutorials/training-a-pointnav-model.md
  - Swapping environments: tutorials/transfering-to-a-different-environment-framework.md
  - Using a pre-trained model: tutorials/running_inference_on_a_pretrained_model.md
  - IL to RL with pipelines: tutorials/training-pipelines.md
- HowTos:
  - Define an experiment: howtos/defining-an-experiment.md
  - Change rewards and losses: howtos/changing-rewards-and-losses.md
  - Define a new model: howtos/defining-a-new-model.md
  - Define a new task: howtos/defining-a-new-task.md
  - Define a new training pipeline: howtos/defining-a-new-training-pipeline.md
  - Visualize results: howtos/visualizing-results.md
  - Run a multi-agent experiment: howtos/running-a-multi-agent-experiment.md
- Projects:
  - BabyAI baselines: projects/babyai_baselines/README.md
  - PointNav baselines: projects/pointnav_baselines/README.md
  - ObjectNav baselines: projects/objectnav_baselines/README.md
  - Advisor code: projects/advisor_2020/README.md
  - Two Body Problem code: projects/two_body_problem_2019/README.md
- FAQ: FAQ.md
- Contributing: CONTRIBUTING.md
- Licence: LICENSE.md

markdown_extensions:
- toc:
    permalink: '#'
- markdown.extensions.codehilite:
    guess_lang: true
- admonition
- codehilite
- extra

# extra_javascript:
#  - javascripts/extra.js
#plugins:
#  - search
#  - mkpdfs
